DiyaEyeCare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include('patient.urls', namespace='patient')),
    path('doctor/', include('doctor.urls', namespace='doctor')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from .views import index, get_otp, verify_otp, save_patient_profile, check_slot_availability

app_name = 'patient'

urlpatterns = [
    path('', index, name='index'),
    path('get-otp/', get_otp, name='get-otp'),
    path('verify-otp/', verify_otp, name='verify-otp'),
    path('save-patient-profile/', save_patient_profile,
         name='save-patient-profile'),
    path('check-slot-availability/',
         check_slot_availability, name='check-slot-availability')
]

users/urls.py
from django.urls import path
from .views import home, login

app_name = 'users'

urlpatterns = [
    path('', home, name='home'),
    path('login/', login, name='login'),
]

patient/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save

# 3rd party module imports
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.


class Patient(models.Model):
    phone_no = PhoneNumberField(null=False, blank=False, unique=True)

    def __str__(self):
        return self.phone_no.as_e164


class PatientProfile(models.Model):
    patient = models.OneToOneField(Patient,
                                   primary_key=True,
                                   on_delete=models.CASCADE,
                                   help_text=('Patient (Required).'),
                                   )
    first_name = models.CharField(max_length=100, default="")
    middle_name = models.CharField(max_length=100, default="")
    last_name = models.CharField(max_length=100, default="")
    age = models.IntegerField(default=0)
    address = models.CharField(max_length=100, default="")
    email = models.EmailField(max_length=100, default="")
    gender = models.CharField(max_length=30, default="Male")
    blood_group = models.CharField(max_length=30, default="")

    def __str__(self):
        return f"{self.patient.phone_no} -> {self.first_name} {self.middle_name} {self.last_name}"


# @receiver(post_save, sender=Patient)
# def create_or_update_patient_profile(sender, instance, created, **kwargs):
#     if created:
#         PatientProfile.objects.create(patient=instance)
#     instance.patientprofile.save()


class OTP(models.Model):
    phone_no=PhoneNumberField(null=False, blank=False)
    secret = models.CharField(max_length=100, default="")
    otp = models.CharField(max_length=100, default="")

    def __str__(self):
        return f"{self.phone_no} -> {self.otp}"

patient/forms.py
from datetime import date, timedelta
import datetime
from django import forms


class CustomDateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d"
        # kwargs["format"] = "%d-%m-%Y"
        super().__init__(**kwargs)


class CustomDateTimeInput(forms.DateTimeInput):
    input_type = "datetime-local"
    #input_type = "datetime"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%dT%H:%M"
        super().__init__(**kwargs)


class ChooseDateForm(forms.Form):
    date = forms.DateField(widget=CustomDateInput(
        format=["%Y-%m-%d"], attrs={
            'min': datetime.datetime.now().date().strftime("%Y-%m-%d"),
            'max': (datetime.datetime.now() + timedelta(days=7)).date().strftime("%Y-%m-%d"),
        }), label="Select Date", required=True, initial=date.today(), error_messages={
            'required': 'Please select date',
    })

patient/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .forms import ChooseDateForm

from .repositories.patient_profile import PatientProfileRepository

from .repositories.patient import PatientRepository

from .models import OTP

from .services.fast2sms import Fast2SMS
from .services.py_otp import TOTP

# Create your views here.


def index(request):
    return render(request, 'patient/index.html')


def get_otp(request):
    if request.method == "POST":
        input_phone_no = request.POST.get("input-phone-no")
        request.session["phone_no"] = input_phone_no
        totp = TOTP.generate_TOTP()
        OTP.objects.create(phone_no=input_phone_no,
                           secret=totp['secret'], otp=totp['otp'])
        message = f"Your One Time Password for booking an appointment  is {totp['otp']}. Please do not share this OTP with anyone. This OTP is valid for 5 minutes. Thank you."
        # Fast2SMS.send_sms(input_phone_no, message)
        return render(request, 'patient/enter_otp.html')


def verify_otp(request):
    if request.method == "POST":
        # input_phone_no = request.POST.get("input-phone-no")
        input_phone_no = request.session["phone_no"]
        input_otp = request.POST.get("input-otp")
        otp = OTP.objects.filter(phone_no=input_phone_no).last()
        print(otp)
        if otp:
            # if otp.otp == input_otp:
            #     return render(request, 'patient/verify_otp.html')
            # else:
            #     return render(request, 'patient/enter_otp.html')
            if TOTP.verify_TOTP(otp.secret, input_otp):
                PatientRepository().create(data={"phone_no": input_phone_no})
                return render(request, 'patient/patient_profile.html')
            else:
                # return HttpResponse("Not Verified")
                return render(request, 'patient/patient_profile.html')
        else:
            return HttpResponse("No OTP found")
    return HttpResponse(TOTP.verify_TOTP(otp.secret, input_otp))


def save_patient_profile(request):
    if request.method == "POST":
        input_first_name = request.POST.get("input-first-name")
        input_middle_name = request.POST.get("input-middle-name")
        input_last_name = request.POST.get("input-last-name")
        input_age = request.POST.get("input-age")
        input_address = request.POST.get("input-address")
        input_email = request.POST.get("input-email")
        input_gender = request.POST.get("input-gender")
        input_blood_group = request.POST.get("input-blood-group")
        print(input_gender)
        data = {
            "first_name": input_first_name,
            "middle_name": input_middle_name,
            "last_name": input_last_name,
            "age": input_age,
            "address": input_address,
            "email": input_email,
            "gender": input_gender,
            "blood_group": input_blood_group

        }
        input_phone_no = request.session["phone_no"]
        patient = PatientRepository().get_by_phone_no(
            phone_no=input_phone_no)
        PatientProfileRepository().update_by_patient(patient, data)
        return HttpResponse("Go to next page")
    return render(request, 'patient/patient_profile.html')


def check_slot_availability(request):
    choose_date_form=ChooseDateForm()
    if request.method == "POST":
        
        choose_date_form = ChooseDateForm(request.POST or None)
        return HttpResponse("Go to next page")
    
    template_context={
        "choose_date_form":choose_date_form
    }
    return render(request, 'patient/check_slot_availability.html',context=template_context)

templates/patient/check_slot_availability.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Check Slot Avaialbility</title>
  </head>
  <body>
    {{ choose_date_form }}
  </body>
</html>

templates/patient/enter_otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enter OTP</title>
</head>
<body>
    <h1>Enter OTP sent to your mobile number</h1>
    <form action="{% url 'verify-otp' %}" method="post">
        {% csrf_token %}
        <!-- <input type="hidden" value="{{ request.session.phone_no }}" name="input-phone-no" id="input-phone-no"> -->
        <input type="text" class="form-input" id="input-otp" name="input-otp" pattern="[0-9]{6}" required>
        <input type="submit" class="btn-submit" id="submit-otp" name="submit-otp" value="Verify OTP">
    </form>
</body>
</html>

templates/patient/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{% static 'css/patient/base.css' %}"
    />
    <title>Patient</title>
  </head>
  <body>
    <h1>Patient Home Page</h1>
    <form action="{% url 'patient:get-otp' %}" method="post">
      {% csrf_token %}
      <input
        type="text"
        class="form-input"
        id="input-phone-no"
        name="input-phone-no"
        pattern="[789][0-9]{9}"
        required
      />
      <input
        type="submit"
        class="btn-submit"
        id="submit-phone-no"
        name="submit-phone-no"
        value="Get OTP"
      />
    </form>
    <!-- <a href="{% url 'patient:get-otp' %}">Get OTP</a> -->
  </body>
</html>

templates/patient/patient_profile.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Patient Demographics</title>
  </head>
  <body>
    <h1>Your mobile number was successfully verfied</h1>
    <p>Please enter your other details to continue</p>
    <form
      action="{% url 'save-patient-profile' %}"
      method="post"
      style="
        display: flex;
        flex-direction: column;
        max-width: 500px;
        margin: 0 auto;
      "
    >
    {% csrf_token %}
      <label for="input-first-name">First Name</label>
      <input
        type="text"
        class="form-input"
        name="input-first-name"
        id="input-first-name"
        required
      />
      <label for="input-middle-name">Middle Name</label>
      <input
        type="text"
        class="form-input"
        name="input-middle-name"
        id="input-middle-name"
        required
      />
      <label for="input-last-name">Last Name</label>
      <input
        type="text"
        class="form-input"
        name="input-last-name"
        id="input-last-name"
        required
      />
      <label for="input-age">Age</label>
      <input type="text" name="input-age" id="input-age" required />
      <label for="input-address">Address</label>
      <textarea
        name="input-address"
        id="input-address"
        cols="30"
        rows="6"
      ></textarea>
      <label for="input-email">Email</label>
      <input
        type="email"
        class="form-input"
        name="input-email"
        id="input-email"
        required
      />
      <div style="display: flex;">
        <label for="">Select Gender</label>
          <input type="radio" id="input-gender-male"
          name="input-gender" value="male" />
          <label for="input-gender-male">Male</label>
          <input type="radio" id="input-gender-female" name="input-gender" value="female" />
          <label for="input-gender-female">Female</label>
          <input type="radio" id="input-gender-other" name="input-gender" value="other" />
          <label for="input-gender-other">Other</label>
      </div>
      <label for="input-blood-group">Blood Group</label>
      <input type="text" class="form-input" name="input-blood-group" id="input-blood-group">
      <input type="submit" value="Proceed to Appointment">
    </form>
  </body>
</html>